services:

  db:
    image: postgres:16.11-alpine3.23
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    restart: always
    shm_size: 256mb

    environment:
      POSTGRES_DB: app
      POSTGRES_USER: login
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080